### ISSUE TITLE
Frontend/Backend Auth Review

### ISSUE THREAD

**Issue by Hubear41** [Hubear41/Hu-sflix#2]
### New account creation, login, and guest/demo login

- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can't use any features without logging in except for movie/series show page

### Notes:
* I'll add an image for the background in the splash and login over the weekend when I do more image editing
* the logout button is temp and will be fixed once I can render a /browse

**Comment by jliversi** [comment]
Overall your app is looking great, just a few relatively minor changes are necessary:

SPLASH
- [ ] Add "Already have an account?" to the left of your sign-in button and move it slightly farther from the top of the page. 
- [ ] Remove the `height: 5000px` from your body. This is currently going to affect all pages on your app and there are definitely pages significantly smaller than 5000px tall.
- [ ] Add a basic footer like netflix's, but instead of the many links (which would be dead links), add links to your github and personal site (the personal site one can be dead for now, you'll build this in the job search)
- [ ] The main splash message should be slightly closer to the Hu'Flix logo. 

SIGNIN
- [ ] Alter the way you're rendering errors to match the way netflix does it on their sign-in page (a yellow box above the form inputs)
- [ ] Add a "show" button on your password input that changes it from type="password" to type="text"
- [ ] Add the guest/demo login button to your sign-in page in addition to your sign-up page.

**Comment by jliversi** [comment]
- [ ] Restyle your login form to match up with the added demo login button (currently it's sticking out of the form). Make sure to account for your new footer as well.
